version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - canonicalheader # don't want to have canonical headers
    - depguard # don't need dependencies restrictions
    - err113 # don't want to use static errors
    - errchkjson # don't want to check encoding error return value in tests
    - exhaustruct # don't want to initialize all struct fields
    - ireturn # want to return interfaces
    - nilnil # want to return nil,nil
    - nlreturn # sometimes don't want to have a blank line before return
    - perfsprint # want to have consistent usage of fmt.Sprintf
    - tagalign # don't want to force tag alignment
    - testpackage # don't want to use separate _test packages
    - wsl # annoying cuddle rules
    - wsl_v5 # annoying cuddle rules
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/gin-gonic/gin.Context).AbortWithError
    funlen:
      lines: 100
      statements: 60
    lll:
      line-length: 180
    revive:
      confidence: 0.8
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - sb strings.Builder
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
        - r *http.Request
        - w http.ResponseWriter
    wrapcheck:
      ignore-sigs:
        - errors.Wrap(
        - errors.Wrapf(
        - errors.New(
        - fmt.Errorf(
        - apperr.New
        - shared.Error
        - (github.com/a-h/templ.Component).Render
        - (*github.com/my-pet-projects/collection/internal/web.ReqRespPair).Render
        - (*github.com/my-pet-projects/collection/internal/web.ReqRespPair).NoContent
        - (*github.com/my-pet-projects/collection/internal/web.ReqRespPair).Redirect
  exclusions:
    rules:
      - path: .*_test.go
        linters:
          - bodyclose
          - cyclop
          - dupl
          - err113
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gosec
          - gosmopolitan
          - lll
          - noctx
          - wrapcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard # captures all standard packages.
        - default # contains all imports that could not be matched to another section type.
        - prefix(github.concur.com) # groups all company-wide imports.
        - prefix(github.com/my-pet-projects/collection) # groups all application-wide imports
