// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/my-pet-projects/collection/internal/model"
	"github.com/my-pet-projects/collection/internal/view/component/ui"
)

type CountriesData struct {
	Countries          []model.Country
	HasBreweries       bool
	PreselectedCountry string
	ShowAllOption      bool
}

func countryToAutocomplete(c model.Country) ui.AutoCompleteData {
	return ui.AutoCompleteData{
		Label: c.NameCommon,
		Value: strings.ToLower(c.Cca2),
		Image: fmt.Sprintf("https://flagcdn.com/%s.svg", strings.ToLower(c.Cca2)),
	}
}

func CountriesAutoComplete(countriesData CountriesData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.AutoComplete(ui.AutoCompleteProps{
			ID:               "country",
			Name:             "country",
			Data:             ui.MapToAutocompleteData(countriesData.Countries, countryToAutocomplete),
			ShowAllOption:    countriesData.ShowAllOption,
			AllOptionLabel:   "All countries",
			AllOptionIcon:    "🌍",
			EventNamespace:   "country",
			ListenToEvents:   []string{"country-selected", "country-cleared"},
			PreselectedValue: strings.ToLower(countriesData.PreselectedCountry),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type CitiesData struct {
	Cities          []model.City
	PreselectedCity string
	ShowAllOption   bool
}

func cityToAutocomplete(c model.City) ui.AutoCompleteData {
	return ui.AutoCompleteData{
		Label: c.Name,
		Value: strconv.Itoa(c.ID),
	}
}

func CitiesAutoComplete(citiesData CitiesData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.AutoComplete(ui.AutoCompleteProps{
			ID:               "city",
			Name:             "city",
			Data:             ui.MapToAutocompleteData(citiesData.Cities, cityToAutocomplete),
			ShowAllOption:    citiesData.ShowAllOption,
			AllOptionLabel:   "All cities",
			EventNamespace:   "city",
			PreselectedValue: citiesData.PreselectedCity,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
